# Generated by Django 4.2 on 2023-04-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('num_value', models.CharField(max_length=100)),
                ('percent_inc_dec', models.FloatField()),
                ('janValue', models.IntegerField()),
                ('febValue', models.IntegerField()),
                ('marValue', models.IntegerField()),
                ('aprValue', models.IntegerField()),
                ('mayValue', models.IntegerField()),
                ('juneValue', models.IntegerField()),
                ('julyValue', models.IntegerField()),
                ('top_emission', models.FloatField()),
            ],
        ),
    ]
