# Generated by Django 4.2 on 2023-04-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_category_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
